export interface EventsSdkOptions {
    url: string,
    environment: string,
    fallbackServer: {
        Domain: string,
        Priority: number,
    },
    loginUrl: string,
    refreshTokenUrl: string,
    servers: string,
    token: string,
    loginType: string,
    forceNew: boolean,
    reconnectionDelay: number,
    reconnectionDelayMax: number,
    maxReconnectAttempts: number,
    timeout: number,
    keepAliveTimeout: number,
    idleInterval: number,
    protocol: string,
    transports: string[],
    upgrade: boolean,
    store: string,
    extensionsModuleName: string,
    queuesModuleName: string,
    dialersModuleName: string,
    serverFetchStrategy: string,
    serverType: number | null,
    useLogger: boolean,
    loggerSocketConnection: string,
    loggerServer: string,
    loggerConfig: {
        logToConsole: boolean,
        overloadGlobalConsole: boolean,
        namespace: string,
        socketEmitInterval: number,
    },
    loggerConnectOptions: {
        reconnection: boolean,
        reconnectionDelay: number,
        reconnectionAttempts: number,
        perMessageDeflate: boolean,
        upgrade: boolean,
        transports: string[],
        debug: boolean
    }
}
