export default {
    LIGHT_GREEN: '#D3E8C6',
    LOGIN_COLOR: '#D5F0E8',
    LOGOUT_COLOR: '#DBDEE2',
    LUNCH_COLOR: '#CDE4F9',
    ADMINISTRATIVE_COLOR: '#B4C1C7',
    PRIVATE_COLOR: '#FFD7D7',
    HOLD_COLOR: '#F5C2CD',
    OTHER_COLOR: '#F3D6EC',
    TRAINING_COLOR: '#DDDFFD',
    TEAM_MEETING_COLOR: '#DFD2F9',
    BRIEF_COLOR: '#CBE4E7'
}
