export default {
    LIGHT_GREEN: '#5EB300',
    LOGIN_COLOR: '#48BB78',
    LOGOUT_COLOR: '#A0AEC0',
    LUNCH_COLOR: '#61B5FF',
    ADMINISTRATIVE_COLOR: '#003B4D',
    PRIVATE_COLOR: '#FF4D4D',
    OTHER_COLOR: '#ED64A6',
    TRAINING_COLOR: '#667EEA',
    TEAM_MEETING_COLOR: '#9F7AEA',
    BRIEF_COLOR: '#1CBBB4',
}
