export default  {
    LINES_TYPE_ID: 1,
    BARS_WITH_LINES_TYPE_ID: 2,
    TIMELINE_TYPE_ID: 3,
    TABLE_TYPE_ID: 4,
    COUNTER_TYPE_ID: 5,  //EXTENSION_CARDS

    REAL_TIME_USER_TABLE_ID: 9,
    STATISTICS_CARDS_TYPE_ID: 55,
    STATUS_CARDS_TYPE_ID: 66,
    CHART_GAUGE_ID: 10,
    CHART_QUEUE_ID: 11,
}
