export default  {
    CHART_LINE_ID: 1,
    CHART_BARS_ID: 2,
    TABLE_TYPE_ID: 4,
    EXTENSION_CARDS_TYPE_ID: 5,
    STATISTICS_CARDS_TYPE_ID: 55,
    STATUS_CARDS_TYPE_ID: 66,
    CHART_GAUGE_ID: 10
}
