export default  {
    LINES_TYPE_ID: 1,
    BARS_WITH_LINES_TYPE_ID: 2,
    TIMELINE_TYPE_ID: 3,
    TABLE_TYPE_ID: 4,
    COUNTER_TYPE_ID: 5,  //EXTENSION_CARDS

    CHART_SPEEDOMETER: 6,
    CHART_QUEUE: 7,
    EXTENSION_CARDS: 9,
    HISTORY_COUNTERS: 10,
    REAL_TIME_TABLE: 11,
}
