export default {
    LINES_TYPE_ID: 1,
    BARS_WITH_LINES_TYPE_ID: 2,
    GANTT_TYPE_ID: 3,
    TABLE_TYPE_ID: 4,
    COUNTER_TYPE_ID: 5,
    CHART_SPEEDOMETER: 6,
    CHART_QUEUE: 7,
    EXTENSION_CARDS: 9,
    HISTORY_COUNTERS: 10,
    QUEUE_DASHBOARD: 11,
    QUEUE_ACTIVE_CALL: 12,
    EXTERNAL_DATA_TYPE_ID: 13,
    QUEUE_COUNTER_TYPE_ID: 14,
    PIE_TYPE_ID: 15,
    RICH_TEXT_EDITOR_ID: 16,

    INFO_TYPE_ID: 222,
}
